apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    name: nginx2
spec:
  containers:
  - name: nginx2
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

      